spring.application.name=crudfull
spring.datasource.url=jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}:XE
spring.datasource.username=${DB_USERNAME:system}
spring.datasource.password=${DB_PASSWORD:123456}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.export.prometheus.enabled=true

